name: ebabil
description: "Ebabil"
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.4.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    flutter_localizations:
        sdk: flutter

    intl: any
    flutter_phone_direct_caller: ^2.1.1
    shared_preferences: ^2.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    generate: true
    uses-material-design: true
    assets:
        - configuration/data/stylesheet.json
